### PR TITLE
Update links for student program

### PR DESCRIPTION
**Pull request by mrmundt**
## Description
Add links / descriptions to the full program for accessibility.

## Checklist:

- [ ] (Committee Chairs Only) I have posted the link for the PR in the usrse slack (#usrse-2024-conference-planning-committee) to ask for content reviewers
- [ ] I have previewed changes locally
- [ ] I have updated the README.md if necessary

cc **ADD GITHUB HANDLES HERE**

### CODE REVIEW

**Comment by mrmundt** [comment]
@dphow - Is this alright?

**Comment by dphow** [comment]
Otherwise looks fine per the local preview I looked at. Thanks!

**Comment by mrmundt** [comment]
I don't know why CircleCI failed. It just... isn't running any of the steps??

**Comment by mrmundt** [comment]
Oh there is a degradation warning for CircleCI. It's not us. Yay.

**Pull request merged**
