### PR TITLE
Add program

### PR DESCRIPTION
**Pull request by jsubida**
## Description

#81 

Formatting using Excel has not been as fun as I had hoped. 

## Checklist:

- [x] (Committee Chairs Only) I have posted the link for the PR in the usrse slack (#usrse-2024-conference-planning-committee) to ask for content reviewers
- [x] I have previewed changes locally
- [ ] I have updated the README.md if necessary

cc **ADD GITHUB HANDLES HERE**

### CODE REVIEW

**Review by diehlpk — APPROVED** [review]
LGTM!

**Review by diehlpk — APPROVED** [review]
LGTM!

**Comment by mrmundt** [comment]
I am going to be mildly persnickety about the formatting, and if you are kind of over it (because I very much remember what that was like), please let me know and I'll take a pass at making it the "color of rock" that I desire:
- We made a "Sessions" page last year so folks could click on a session link and go see the things in that session
- The titles being on the program is actually important. In this current form, there is no information about what actually falls under each heading!
- Can you please add the registration links for the tutorials?

**Review by mrmundt — CHANGES_REQUESTED** [review]
(See other comment I left that I forgot to do as a "Review comment")

**Review by mrmundt — APPROVED** [review]

**Comment by jsubida** [comment]
@mmundt  YOU ARE AN EXCEL GURU. This looks great! What do you think about adding '-' or bullets to make the titles easier to differentiate? 
image

**Comment by mrmundt** [comment]
> @mmundt YOU ARE AN EXCEL GURU. This looks great! What do you think about adding '-' or bullets to make the titles easier to differentiate? image

Seems like a good idea :) Haaavveee at it!

**Comment by jsubida** [comment]
@mmundt Done!

**Comment by danielskatz** [comment]
preview: https://output.circle-artifacts.com/output/job/82d4b1e9-f800-43b9-b493-ef7817bb560b/artifacts/0/usrse.github.io/usrse24/program/index.html

**Comment by danielskatz** [comment]
something looks a bit off here: Screenshot 2024-08-10 at 14 49 55

**Comment by danielskatz** [comment]
As some general comments,

1. it would be nice to know which talks are abstracts and which have an associated paper.
2. can we list authors (at least speakers), not just talk titles?

I guess none of these are important to do immediately though

**Comment by danielskatz** [comment]
preview of details: https://output.circle-artifacts.com/output/job/82d4b1e9-f800-43b9-b493-ef7817bb560b/artifacts/0/usrse.github.io/usrse24/program/sessions/index.html

**Comment by danielskatz** [comment]
In the sessions page, it would also be nice to know which are talks and which are papers

**Comment by mrmundt** [comment]
> As some general comments,
> 
> 1. it would be nice to know which talks are abstracts and which have an associated paper.
> 2. can we list authors (at least speakers), not just talk titles?
> 
> I guess none of these are important to do immediately though

Authors in the table make it very cluttered. I tried it last year, and it was way too much. So I'd prefer not for readability purposes.

Talks vs. Papers vs. Notebook is fine to put on the Sessions page. @jsubida - can you please do that? I am now away from my computer for a few hours.

**Comment by danielskatz** [comment]
I'm going to disagree

> Authors in the table make it very cluttered. I tried it last year, and it was way too much. So I'd prefer not for readability purposes.

This might be, but I also think it's important to have peoples names appear at this level. I'm not sure how to do it in a non-cluttered way.

**Comment by mrmundt** [comment]
> I'm going to disagree
> 
> > Authors in the table make it very cluttered. I tried it last year, and it was way too much. So I'd prefer not for readability purposes.
> 
> This might be, but I also think it's important to have peoples names appear at this level. I'm not sure how to do it in a non-cluttered way.

Can you please send me specifically the list of presenters? I don't have access to that information.

**Comment by danielskatz** [comment]
We don't actually have it - we just have the list of authors. We would have to ask for each who will present it. Which we can do later...

**Comment by mrmundt** [comment]
> We don't actually have it - we just have the list of authors. We would have to ask for each who will present it. Which we can do later...

Yup. We will table that discussion for later then. I just pushed the changes to put the presentation type on the Sessions page.

**Comment by mrmundt** [comment]
- Preview of Sessions: https://output.circle-artifacts.com/output/job/490a13a8-e457-4b9a-92c5-d92fc65b8176/artifacts/0/usrse.github.io/usrse24/program/sessions/index.html
- Previous of Program: https://output.circle-artifacts.com/output/job/490a13a8-e457-4b9a-92c5-d92fc65b8176/artifacts/0/usrse.github.io/usrse24/program/index.html

**Pull request merged**
