### PR TITLE
Add GitLab as gold sponsor

### LINKED ISSUE #28: Abbey Roelofs submitted a request due 2024-04-17
**Request type**: 

- [ ] Website change / addition

**Email** aheinlei@umich.edu

**Purpose** Add the GitLab logo as a gold sponsor on the website

**Content**  https://drive.google.com/drive/u/0/folders/1PASh2dknevA6l7wzUT9c0gjxXArvjLpQ 

- [ ] I've informed the requestor that this is complete

### PR DESCRIPTION
**Pull request by jsubida**
## Checklist:

- [ ] (Committee Chairs Only) I have posted the link for the PR in the usrse slack (#usrse-2024-conference-planning-committee) to ask for content reviewers
- [x] I have previewed changes locally
- [ ] I have updated the README.md if necessary

cc **ADD GITHUB HANDLES HERE**

Closes #28

### CODE REVIEW

**Comment by jsubida** [comment]
image

**Comment by roelofsaj** [comment]
Thanks for getting this up! The GitLab logo kind of dwarfs the Globus one, though... I know it's probably going to take up more space just because of its aspect ratio, but could it be a little smaller?

**Comment by jsubida** [comment]
I think putting them side-by-side will help with perceived size differences. Perhaps a more sustainable solution would be to require a square icon for future sponsors? That way, wider logos won't appear bigger than their slimmer siblings. 
image

**Comment by mrmundt** [comment]
> I think putting them side-by-side will help with perceived size differences. Perhaps a more sustainable solution would be to require a square icon for future sponsors? That way, wider logos won't appear bigger than their slimmer siblings. image

FWIW, some places are very specific about having their name paired with the logo which makes it impossible to have as a square. So @roelofsaj ask for multiple versions if you can!

**Comment by jsubida** [comment]
Ah. Good point @mrmundt. Alternative solution? 
image

**Comment by roelofsaj** [comment]
I agree it's better, but the font & logo both still look overly large compared to the others on the page. 

And thanks for the suggestion, @mrmundt -- I'll ask for additional options in future!

**Comment by jsubida** [comment]
@roelofsaj 
image

**Comment by jsubida** [comment]
image

**Comment by mrmundt** [comment]
@jsubida - Oooo I like it now. Yes yes. Good good. A+.

**Review by mrmundt — APPROVED** [review]

**Pull request merged**
