### PR TITLE
Add BOF and workshop titles

### LINKED ISSUE #41: Josh Teves submitted a request due 2024-05-20
**Request type**: 
- [x] Website change / addition
- [x] Email to conference listserv
- [x] Add to monthly US-RSE newsletter
- [x] Social media blast (LinkedIn, Mastodon, X/Twitter)
- [x] Slack

**Email** jbteves@sandia.gov

**Purpose** Announce First Program Additions

**Content**  https://docs.google.com/document/d/1dZsmt_Inlgf8Tzaje-4JLi1A_px3rCZY8e0WfSygKH4/edit?usp=sharing 

- [ ] I've informed the requestor that this is complete

### PR DESCRIPTION
**Pull request by jsubida**
## Description

Closes #41. Displays titles of accepted BOFs and workshops

## Checklist:

- [] (Committee Chairs Only) I have posted the link for the PR in the usrse slack (#usrse-2024-conference-planning-committee) to ask for content reviewers
- [x] I have previewed changes locally
- [ ] I have updated the README.md if necessary

cc **ADD GITHUB HANDLES HERE**

@jbteves-sandia Feel free to merge as-is, but if you want to include the descriptions, I can make those changes!

### CODE REVIEW

**Review by mrmundt — CHANGES_REQUESTED** [review]
Can you please also update the navigation menu? For US-RSE'23, we had all the types of accepted stuff in the nav dropdown: 
- https://github.com/USRSE/usrse23/blob/main/_data/navigation.yml
- https://github.com/USRSE/usrse23/blob/main/_data/menus/program.yml

**Comment by jbteves-sandia** [comment]
We're skipping descriptions for now, some of them are formatted differently and people ended up being very heterogeneous with what I thought (mistakenly) was a clear format.

**Comment by jsubida** [comment]
@mrmundt Breaking the rules and addressing [another issue](https://github.com/USRSE/usrse24/issues/44) with this pull request. I accept the punishment for this transgression. Or advice for what to do next time. Or both.

**Comment by mrmundt** [comment]
I am 90% certain that the link failure is transient.

**Comment by mrmundt** [comment]
> @mrmundt Breaking the rules and addressing [another issue](https://github.com/USRSE/usrse24/issues/44) with this pull request. I accept the punishment for this transgression. Or advice for what to do next time. Or both.

My software engineering side is appalled. But my practical side does not care. And the practical side generally wins. So _this was a good choice, A+_.

**Review by mrmundt — APPROVED** [review]

**Pull request merged**
